### ISSUE TITLE
Error when creating background subtracted .chi/.dat files

### ISSUE THREAD

**Issue by spearsdp** [Dioptas/Dioptas#202]
When auto processing TIFF images, to create .dat and .chi files i get the following error: 
![error dioptas](https://github.com/Dioptas/Dioptas/assets/56171084/f525fee3-fa04-4d80-86c5-0069127aded7)

And it will not create nor save the background subtracted files.

**Comment by spearsdp** [comment]
Actually, I get this error, every time I click a button, or try to do anything in the program.

**Comment by CPrescher** [comment]
Hi,

thank you for reporting the bug. It has been previoulsy reported in #197 and is already fixed in the develop branch. Thus, a new release will solve the issue. I guess when it is happening once, every change you do will also trigger resaving, and therefore you get more errors.

Best wishes,
Clemens
